{% set name = "napari-pims-bioformats" %}
{% set version = "0.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari-pims-bioformats-{{ version }}.tar.gz
  sha256: f79b10d6f114746d7e8dfbc4376db285cf8751d0689bd1d3839aadb64e5f6d76

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools_scm
  run:
    - jpype1
    - napari-plugin-engine >=0.1.4
    - numpy
    - pims
    - python >={{ python_min }}
    - openjdk

test:
  imports:
    - napari_pims_bioformats
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/tlambert03/napari-pims-bioformats
  summary: PIMS bioformats plugin for napari
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tlambert03
